4a-hal-*: use correct config files, introduce runtime detection
Use config files shipped in 4a-hal-generic and 4a-hal-unicens
(+ HAL for greenbox from layer).

Add runtime detection script '4a-hal-setup' as ExecPre in 4A service

Change-Id: Ibc44bd636a105d0ca33956e99a44defc480a0d0e
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/meta-agl-early/recipes-multimedia/4a-hal-generic/files/4a-hal-setup b/meta-agl-early/recipes-multimedia/4a-hal-generic/files/4a-hal-setup
--- a/meta-agl-early/recipes-multimedia/4a-hal-generic/files/4a-hal-setup
+++ b/meta-agl-early/recipes-multimedia/4a-hal-generic/files/4a-hal-setup
@@ -1,12 +1,38 @@
 #!/bin/bash
 
 # this script will setup the appropriate HAL config files depending on what HAL has to be enabled
-HALDIR=/usr/libexec/agl/4a-hal/
+HALDIR=/usr/libexec/agl/4a-hal
 
 MYNAME=$(basename $BASH_SOURCE)
 function info() { echo "$MYNAME: $@" >&2; }
+function warning() { echo "$MYNAME: WARNING: $@" >&2; }
+function error() { echo "$MYNAME: ERROR: $@" >&2; return 1; }
 
 set -e
+
+CONFIG=${1:-$HALDIR/default_hals.conf}
+
+info "Using default config $CONFIG"
+
+[[ ! -f $CONFIG ]] && warning "Config file '$CONFIG' doesn't exist."
+
+# default values
+HAL_FALLBACK="2ch-generic-usb"
+HAL_DEFAULT=""
+HAL_AUTODETECT="yes"
+. $CONFIG || error "Invalid config file '$CONFIG'"
+
+info "Platform HALs: $HAL_DEFAULT"
+
+if [[ "$HAL_AUTODETECT" == "yes" ]]; then
+	info "Autodetecting most appropriate HAL..."
+	# TODO
+fi
+
+[[ -z "$HAL_DEFAULT" ]] && {
+	info "No hal found. Using fallback $HAL_FALLBACK"
+	HAL_DEFAULT="$HAL_FALLBACK"
+}
 
 # create hal config dir if it doesn't exist yet
 mkdir -p $HALDIR/etc
@@ -15,18 +41,15 @@ mkdir -p $HALDIR/etc
 rm -f $HALDIR/etc/*.json || true
 
 # enable all specified HALS on command line
-info "called with hals: $@"
-for hal in "$@"; do
-	# argument can be:
-	# - hal full filename
-	# - hal relative filename
-	# - hal abbreviation
-	for file in $hal $HALDIR/etc.available/${hal}.json $HALDIR/etc.available/hal-4a-${hal}.json; do
-		[[ -f $file ]] && {
-			cp -f $file $HALDIR/etc/
-			break
-		}
-	done
+info "Activating HALs: $HAL_DEFAULT"
+for hal in $HAL_DEFAULT; do
+	halfile=$HALDIR/etc.reference/hal-4a-${hal}.json
+	[[ -f $halfile ]] && cp -f $halfile $HALDIR/etc/ || warning "File for HAL $hal not found"
 done
 
-info "The following hals are enabled: $(cd $HALDIR/etc; ls)"
+info "The following hals are enabled in $HALDIR/etc:"
+pushd $HALDIR/etc >/dev/null 
+for x in *.json; do
+	info "   - $x"
+done
+popd >/dev/null
